# THIS FILE IS IN YAML FORMAT. PLEASE PAY ATTENTION TO THE WHITESPACE FORMATTING, AS IT IS IMPORTANT.
#
# PLEASE SEE DOCUMENTATION FOR THE TacacsPlus::Server CLASS FOR A COMPLETE LIST OF CONFIGURATION OPTIONS.


#### NETWORK OBJECT GROUPS ####
:network_object_groups:

  datacenter1:
  - 10.0.0.0/15
  - 10.2.0.0/16




#### SHELL COMMAND OBJECT GROUPS ####
:shell_command_object_groups:

  basic configuration:
  - ^description .*
  - ^duplex .*
  - ^interface .*
  - ^no shutdown <cr>$
  - ^shutdown <cr>$
  - ^speed .*
  - ^switchport access vlan [0-9]+ <cr>$
  - ^switchport trunk allowed vlan add [0-9]+ <cr>$
  - ^switchport trunk allowed vlan remove [0-9]+ <cr>$
  - ^write <cr>$
  - ^write memory <cr>$
  - ^shutdown <cr>$

  show:
  - ^show .*
  - ^write terminal <cr>$
  - ^do show .*
  - ^ping .*
  - ^terminal monitor <cr>$
  - ^traceroute .*

  whitelist:
  - login
  - exit




#### ACCESS CONTROL LISTS ###
:acls:

  deny all:
  - :permission: deny
    :ip: any

  permit all dc:
  - :permission: permit
    :network_object_group: datacenter1
  - :permission: permit
    :ip: 10.9.9.0
    :wildcard_mask: 0.0.0.255

  permit localhost:
  - :permission: permit
    :ip: 127.0.0.1




#### COMMAND AUTHORIZATION PROFILES ####
:command_authorization_profiles:
  read only:
  - :shell_command_object_group: show


  basic user:
  - :shell_command_object_group: show
  - :acl: permit all dc
    :command: ^configure terminal <cr>$
  - :acl: permit all dc
    :shell_command_object_group: basic configuration

  advanced user:
  - :command: .*

  localhost:
  - :acl: permit localhost
    :command: .*



#### COMMAND AUTHORIZATION WHITELIST ####
:command_authorization_whitelist: 
  - :shell_command_object_group: whitelist



#### AUTHOR AVPAIRS ####
:author_avpairs:
  basic user:
  - :acl: permit all dc
    :service: shell
    :avpairs:
    - idletime=5
    - timeout=30
  - :acl: permit localhost
    :service: shell
    :avpairs:
    - priv-lvl=15

  localhost:
  - :acl: permit localhost
    :service: shell
    :avpairs:
    - priv-lvl=15

  restrictive:
  - :service: shell
    :avpairs:
    - idletime=1
    - timeout=1

  loose:
  - :service: shell
    :avpairs:
    - priv-lvl=15



#### USER GROUPS ####
:user_groups:
  read only:
    :command_authorization_profile: read only
    :enable_acl: deny all
    :author_avpair: restrictive

  basic user:
    :command_authorization_profile: basic user
    :author_avpair: basic user

  advanced user:
    :command_authorization_profile: advanced user
    :author_avpair: basic user




#### USERS ####
:users:
  user1:
    :encryption: sha1
    :salt: V5AVgebMv9u50toy9VXEgabeHhgpWnDo
    :enable_password: 259ef5def42d8c29c67242b551887bad4cd12f1d  #password
    :login_password: 259ef5def42d8c29c67242b551887bad4cd12f1d  #password
    :user_group: advanced user
    :author_avpair: loose

  user2:
    :encryption: clear
    :enable_password: password
    :login_password: password
    :user_group: basic user

  user3:
    :encryption: clear
    :enable_password: password
    :login_password: password
    :user_group: read only

  user4:
    :command_authorization_profile: localhost
    :encryption: clear
    :enable_password: password
    :enable_acl: permit localhost
    :login_acl: permit localhost
    :login_password: password
    :author_avpair: localhost

  user5:
    :encryption: clear
    :enable_password: password
    :login_password: password
    :login_password_lifespan: 30
    :enable_password_lifespan: 30

  user6:
    :encryption: clear
    :enable_password: password
    :login_password: password
    :login_password_lifespan: 30
    :login_password_expires_on: "2008-01-01"
    :enable_password_lifespan: 30
    :enable_password_expires_on: "2008-01-01"


#### TACACS DAEMON ####
:tacacs_daemon:
  :ip: 127.0.0.1
  :key: s0mek3y
  :log_level: 0
  :login_prompt: |-
    Company XYZ
    User Access Verification.
    username: 
  :port: 4949
  :password_prompt: "Password Verification\npassword: "
  :delimiter: "\t"
