--- 
:description: shell settings. user dustin

:client_log: []

:server_log: 
- "msg_type=TacacsPlus::Server\tmessage=Starting TACACS+ server (Offline Testing Mode)."
- "msg_type=Authorization\tmessage=User issued the following AVPairs: priv-lvl=15\tstatus=Pass Add\tclient=127.0.0.1\tauthen_method=TACACS Plus\tauthen_type=ASCII\tport=tty1\tpriv_lvl=1\trem_addr=xxxxxxxxxxx\tservice=Login\tuser=dustin"

:client_dialog: 
- !ruby/struct:TacacsPlus::PacketStruct
  header: !ruby/object:TacacsPlus::TacacsHeader
    flags: 0
    length: 48
    major_version: 12
    minor_version: 0
    seq_no: 1
    session_id: 799642903
    type: 2
  body: !ruby/object:TacacsPlus::AuthorizationRequest
    arg_cnt: 2
    arg_lens:
    - 13
    - 4
    args:
    - service=shell
    - cmd*
    authen_method: 6
    authen_type: 1
    port: tty1
    port_len: 4
    priv_lvl: 1
    rem_addr: xxxxxxxxxxx
    rem_addr_len: 11
    service: 1
    user: dustin
    user_len: 6

:server_dialog: 
- !ruby/struct:TacacsPlus::PacketStruct
  header: !ruby/object:TacacsPlus::TacacsHeader
    flags: 0
    length: 18
    major_version: 12
    minor_version: 0
    seq_no: 2
    session_id: 799642903
    type: 2
  body: !ruby/object:TacacsPlus::AuthorizationResponse
    arg_cnt: 1
    arg_lens:
    - 11
    args:
    - priv-lvl=15
    data_len: 0
    server_msg_len: 0
    status: 1